short_open_tag = Off
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE
upload_max_filesize = 50M
memory_limit = 2048M
max_execution_time = 300
max_input_vars = 1500
expose_php = Off
date.timezone = Asia/Yangon
enable_dl = Off
allow_url_fopen = Off
allow_url_include = Off
display_errors = Off
post_max_size = 50M
session.cookie_secure = 1
upload_tmp_dir = /tmp
precision = 14
